version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
        read_only: true